### ISSUE TITLE
Suppress strange FE output when output filter deactivated

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#159]
if "CSS-, JS-, Meta-Insert-Filter" is inactive, in frontend "[[Title]] [[Metas]] [[Css]] [[Js?pos=HeadTop]] [[Js?pos=HeadLow]] [[Js?pos=BodyTop]] [[Html?pos=BodyTop]] " shows up. This must not happen!

**Comment by NorHei** [comment]
ahhh this one was missing in my list ...

**Comment by NorHei** [comment]
Öhm ... isnt there a setting for this in the Outputfilter settings ?

"Try to add placeholder for insert filter if they do not exist:"

![screenshot - 19 11 2016 - 12 37 40](https://cloud.githubusercontent.com/assets/1908651/20455153/296b4b2a-ae55-11e6-9e7f-5d7b25d87247.png)

**Comment by instantflorian** [comment]
I see.

I guess my "mistake" shows the urgent need of a massive optimization of 
the usabilty of the filter configuration. So if even I do not understand 
what a filter does and how they work together I guess a normal user will 
be completely confused.

Currently, all this filter stuff seems to me to be not very helpful, 
maybe all this should be removed from the default installation and 
should be only offered as an addon to those porofessional users who 
really need this and know how to use it.


------ Originalnachricht ------
Von: "NorHei" <notifications@github.com>
An: "WBCE/WebsiteBaker_CommunityEdition" 
<WebsiteBaker_CommunityEdition@noreply.github.com>
Cc: "instantflorian" <info@meerwinck.com>; "Author" 
<author@noreply.github.com>
Gesendet: 19.11.2016 12:39:25
Betreff: Re: [WBCE/WebsiteBaker_CommunityEdition] Suppress strange FE 
output when output filter deactivated (#159)

**Comment by NorHei** [comment]
Thats why we put the filter on Autopilot.  A normal user does not  need to play whith those settings . 

Insert filters are needed to have modules using dynamic Javascript , best example may be the colorbox that has about 10 different and very interesting templates , but its almost impossible to switch those Templates from the BE. Yess you can do it but you have to use pretty unrelieable workarounds. (That die on each module upgrade)

Another thing is about the usage of insert and include for Jquery they are completely deprecated and won't function on future versions of Jquery. (BTW they slow down the whole loading of Javescript and only work whith Jquery. Thats part of the reason there are only Jquery dependant Module) 

Another problem is that if a Modules load their own version of jquery , there is not the slightest way to check if Jquery is already loaded , though i had module-template combinations that tried to load Jquery 6 times in different versions. Thats why a central instance is needed to manage this.   

Filter like CSS to head where always present in WB and caused a  lot of support requests because they could not be dactivated , exept from the class insert  Filters and Stefeks BE Droplets , all other filter where always present but could onl be configured by changing the Core (a thing you loose on each upgrade) That always caused trouble  now you can simply turn them on and of whith the click on a button. 

A far more elegant soloution would be the use of something like OPF Dashboard as that would enable Modules to install and manage their own filter constructs. 

Usage examples OPF: 

- BBcode , using bb code in comments , or modules , ore whatever you like. 
- Markdown support , same as whith  BBcode. 
- Building automated REST interfaces as you can suppress normal output and convert it to Json
- Bad Word filter.  
- HTML Tidy , automation for Cleaning up yout HTML 
- Auto Links for SEO (Converting certain Words into Links , or add strong and i tags )
- Cass Insert ;-)
- How about a JS to head
- CSS to Head , i think its pretty usefull . 
- Better hiding of email Filter 
- Auto scaling of images (configurable for certain modules/pages/whole page...)
- Short URL as a module. 
- Multidomain suppport as a Module.  
  

Usage examples Class Insert(I):

- Colorbox whith Template Selector in BE 
- Admintool to organize color/display Stylesettings for a Frontend Template(or BE template).
- Loading Javascriot modules whith configurable settings. 
- Cookie Warning as a module , suitable for every template , even old ones, whith configurable behavior and color settings.   
- Configurable Debug Output as popup on pages FE/BE. 
- Easy! CSS configuration for Galleries and so on. 
- Even Droplets can Affect CSS and JS. 
- Ever tried to load multiple scripts Via  frontend.js ...a nightmare
- Loading scripts dynamic(Depending on BE settings) via  frontend.js almost impossible. 
- We need simplepagehead for halfway usefull header, but this only supports modules it knows. 
- JQ Tablesorter , whith configurable Display in BE.
- Joading JS only if a snipppet is actually used, not just loaded  
- Adding a loginbox popup to the Page if not logged in 
...

Good outputfilter and the Option to controll your JS from the Core Engine are two concepts that really needed badly if you want to see any progress.  
 
If you think we should hide some of those Settings i have no problem whith this , i already thought of that myself.  But not having those settings made me cry of frustration back in the times i used WB as a foundation for building Webapplication. ...:-(

**Comment by NorHei** [comment]
Btw, if you go and change the Pages folder in the BE settings you would do much more harm to your page... other Settings would be more fatal too. You can't stop some people from hurting themself.

**Comment by NorHei** [comment]
Btw one of the next steps would be to integrate OPF dashboard , where each filter gets a decent description. Please no worry again, as this gets a simplifyed settings and an extended , where you can controll almost everything about the filter .
