### ISSUE TITLE
What to add to the bundle?

### ISSUE THREAD

**Issue by webbird** [WBCE/WebsiteBaker_CommunityEdition#2]
First thing to do will be to replace the FCK with latest CKE module. But what else?

* Replace the old Backend Theme with the enhanced one? Or just _add_ the advanced one but leave the old one as default?
* Replace News with Topics?
* Replace Form with Form2?
* Any other?

**Comment by instantflorian** [comment]
* Replace classic theme with flat theme, but leave Argos Theme as alternative choice
* News should be replaced by topics, topics should be pre-configured nicely
* Form2 seems to be rather old, I would prefer minform (with some nice ready form templates)
* add simplepagehead
* add wbstats
* add cwsoft-AFE
* add code2 (replace code?)
* add pagecloner (but it has to be fixed first, module generates empty titles of the copied pages due to php issues)
* add backup module
* add sitemap module
* add WB SEO tool
* add colorbox 1.6
* add AddonMonitor
* include google_sitemap.php in root
* update droplets to 1.73
* replace default frontend template with better ones 

* switch "Secure form switcher" to multitab by default and deactivate fingerprinting by default

Advanced enhancements:
* TurboPageTree Patch
* named sections
* Shotrurl

**Comment by webbird** [comment]
Just a note according AFE... We had a path traversal vulnerability in BlackCat CMS that allowed to download the config.php. The attacker was able to change the backend login of the admin user and used the AFE then to upload malware. So the AFE is (can be) kind of dangerous.

**Comment by webbird** [comment]
- [ ] Replace classic theme with flat theme, but leave Argos Theme as alternative choice
- [ ] News should be replaced by topics, topics should be pre-configured nicely
- [ ] Form2 seems to be rather old, I would prefer minform (with some nice ready form templates)
- [ ] add simplepagehead
- [ ] add wbstats
- [x] add cwsoft-AFE
- [ ] add code2 (replace code?)
- [ ] add pagecloner (but it has to be fixed first, module generates empty titles of the copied pages due to php issues)
- [ ] add backup module
- [ ] add sitemap module
- [ ] add WB SEO tool
- [ ] add colorbox 1.6
- [ ] add AddonMonitor
- [ ] include google_sitemap.php in root
- [x] update droplets to 1.73
- [ ] replace default frontend template with better ones
- [ ] switch "Secure form switcher" to multitab by default and deactivate fingerprinting by default

**Comment by webbird** [comment]
ShortURL = this one -> http://forum.websitebaker.org/index.php/topic,17725.0.html ?

**Comment by instantflorian** [comment]
yes

**Comment by webbird** [comment]
Added TurboPageTree Patch & named sections

**Comment by webbird** [comment]
Added Shorturl

**Comment by NorHei** [comment]
Maybe add multilanguage pack?

**Comment by webbird** [comment]
Can you give me a link?

**Comment by NorHei** [comment]
http://forum.wbce.org/viewtopic.php?pid=71

The first one is the original from Dietmar, the second one is the one i used in my old fork of wb. I just added security validation and some readme stuff as far as i remember. The folder is an Mercurial project so you can easyly check the changes whith TortoiseHG.

BTW. Just wanted to say : GOOD JOB SO FAR!!!!

**Comment by WebDesignWorx** [comment]
Hello, 
regarding the TurboPageTree:
I see you used the older version.
There was a newer one but I don't remember whether or not I ever uploaded it to the forum.
It returned an array instead of the whole spaghettish HTML PHP mixage. The array could then be pulled through a template (making it easier to change the layout of the PageTree). I used Twig for the Template, but plain PHP could be applied instead just fine.

Stefek

**Comment by WebDesignWorx** [comment]
Twig in general.
Please consider making an individual module (or include package) for the Twig TE.
2 of the shipped modules use this TE and there may follow further ones.
Since it is already used, having it shipped as separate module, may be good solution.
(So this is a suggestion for: what to add to the bundle)

Stefek

**Comment by NorHei** [comment]
How about posting that version on WBCE Forum? Or maybe sendt it via mail ?

**Comment by WebDesignWorx** [comment]
I may send it to you, but the template I used was done using Twig (but as I said, it could be adapted for use with plain php, but I wouldn't do that, at least not currently, as I have only little time at the moment).

Give me some days and I will try to find it on my backup drives.

**Comment by NorHei** [comment]
Great waiting for it!

**Comment by webbird** [comment]
PageTree: I used the only version we - aka florian - were able to find, as the attachments in the WB forum are all gone. Please send me the latest one so I can update it.

I close this issue now because it's getting a bit off topic. ;) It was meant for the initial version which should be released "as is" before starting to add more.
