### ISSUE TITLE
Default Template can't be selected in page settings 

### ISSUE THREAD

**Issue by marmotwb** [WBCE/WebsiteBaker_CommunityEdition#23]
When default template ist set to WBCE and you select this template in page settings you get the message that the setting is saved but in fact default template ist saved. This might matter when someone wants to make sure that the page template does not change when the default is changed. And of course the saved message is wrong.

**Comment by WebDesignWorx** [comment]
The message should say: "The selected template is currently the default template." or some such. I wouldn't let the save process save the actual Template as setting if it is already installed as default. 
This because, when you allow it, you can forget about it later (sure you could use the Addon-Monitor to see which page is using what Template, but without it... happy fishing.)
It's much better to install the same template with a different name/directory and select this when you know you want to change the overall default later, but stick to this on selected pages.
Just my thoughts, but I wouldn't change the way it is now.
I would change the on-save-message though, as the editor should be informed why his selection was not saved/performed.

**Comment by marmotwb** [comment]
Hi, thanks for comment. 
"This because, when you allow it, you can forget about it later " that's exactly how wb people think. The big programmers protect the clumsy user from the bad bad world. The standard template ist set by default so if someone wants to change, there might be reasons. But the user is not able to set what he wants. What if the user thinks about setting now and forgets about that later? What if the user sets a different template and forgets about this later? Thats why this is a bug for me and I don't see the point in your agruments.
I agree that this is not an important question but I found while testing.
And surely others have different opinions.

regards

**Comment by WebDesignWorx** [comment]
Yes, this is of course my opinion. My perspective on this is, it should stay as it is... until, of course, an overwhelming majority of users sees it as a bug. My above scenario was delivered as a cms user, not in any way from a developer, let alone "big programmer", standpoint.

I agree with you that there should be an appropriate notification. That's what I as a cms user would minimally expect in order to understand, and maybe even learn to  appreciate, the mechanic involved.

**Comment by webbird** [comment]
Uhm, so the request is to allow to set the default template explicitly for a page? If yes, should there be an "Are you sure?" message before saving? Or a note after saving? Or both?

**Comment by WebDesignWorx** [comment]
This would be an option aswell. In any case, the user should be informed about the consequences. Don't forget, you can't see easily where Templates have been asigned and making it easy for the uninformed/unexperienced user to change the template to the one that is currently "default", can result in unintentioned surprise.
We have a classic example of feature Vs. bug depending on point of view, rather than technological imperfection.
:-)

**Comment by webbird** [comment]
I'm sure the behaviour is "by design", so it's an enhancement / feature wish, not a bug. I've never seen a request like this in the WB forum, but I'm the last one to be "up-to-date" concerning that forum.

**Comment by WebDesignWorx** [comment]
Yes, it's by design (for good reasons IMO). If it's an `enhancement`, is surely determined by point of view. In my opinion it can lead to unsatisfactory complications. If it were me to decide, I would rather make it an option (in general settings). But then again, if the end-user is informed, it is fine to make it default.

**Comment by marmotwb** [comment]
My request was to give the user what he selects.
If you select a setting, save the setting and the saving is confirmed but the result is different, to me this is a bug, even if it's inserted intentionally.
Sorry, I still don't get the point here. If you allow to set any template, why are there problems to allow to set the standard template? Becuase the user doesn't see the result?
In the dorpdown the user can choose between default Template or an explicit template.
If you don't want to allow, just delete the standard template from the dropdown.
My experience is, that "Are you sure" questions are confirmed by most users without tinking twice.
Btw. the "feature" was introduced with [rev 1494](http://project.websitebaker.org/projects/wb28x/repository?utf8=%E2%9C%93&rev=1494) (line 66) and is not even documented or reasoned. It was just a brain wave form a wb developer who surely knows better what the user wants than the user itself.

To me the facts here are rather clear and it's not worth discussing hours. That's the point where even a communitiy edition needs someone who makes a decision, whatever it will look like.

**Comment by WebDesignWorx** [comment]
__"If you don't want to allow, just delete the standard template from the dropdown."__

I would make it visible, but `disabled` (selectable only when in GeneralSettings this behaviour is activated).
So all scenarios are possible.

**Comment by webbird** [comment]
What was the behaviour before rev 1494? Is that the required behaviour?

Before making a decision it's my personal habit to collect all the facts and opinions first. But maybe the better place for this discussion would be the forum.

**Comment by webbird** [comment]
Woops, hit wrong button. *blush*

**Comment by WebDesignWorx** [comment]
I don't remember, but I think, you've been able to select and save (overwrite `default_template` with `template_name`) - just what Marmot sees should still work as it was.
I agree that it is a bug in so far, that the item is selectable, you select it, but it isn't saved and you're not even informed about the reasons.
Depending on point of view it is but a welcome feature (for reasons I described before).
For a real _improvement_ I would make another setting in GeneralSettings, with "unselectable" (not able to overwrite with the same template as default_template) by default.
This is my suggestion, my arguments and in this case any scenario would be served.
I'm not interested in discussion so much, or superimposing my point of view.
Just sharing some suggestions regarding this specific feature.
Forum: yes, consult the community by exactly presenting the behaviour as it is now and how they would like it to be. I don't think it's about discussion, really. More a brain storming activity to pick the best possible and satisfactory solution. ^^

**Comment by marmotwb** [comment]
Hi,

"Depending on point of view it is but a welcome feature (for reasons I described before)."
As far as I see the only reason you mentioned is that the user can forget about this setting. But the user can forget this setting no matter which template he selected. So this is no argument for me.
Adding a general option or discussing in the forum is complete overkill in my opinion. It's simply not important enough.

Maybe the best is to close this here and perhaps in one or two years anybody else comes across this, commtis the deleting of line 66 and nobody will ever  notice. ;).

**Comment by WebDesignWorx** [comment]
_"But the user can forget this setting no matter which template he selected. So this is no argument for me."_
Yes, but he can do it incidently as well:
he tries another template
wants to go back to default but instead he selects "MyTemplate" (which is the current default).
Later he changes the default template, but he does not realize that somewhere on level 5 he has a page where he incidentally has overwritten the default template setting.

I'm looking for a solution that would satisfy all different scenarions, including yours.

**Comment by NorHei** [comment]
Would it help to have the selector look like this:

Use system wide default template
------------------------------------------------
Blank 
Css2
Green Lush
WBCE

**Comment by marmotwb** [comment]
No more activity here. So I fixed the issue without spending more usesless time on it. I'm rather sure this fix will cause no problems. If it does, we can revert an you can blame me.
