### ISSUE TITLE
Update 1.1.11 => 1.2 generates unwanted output

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#241]
If a page is updated from WBCE 1.1.11 to 1.2, during the update process warnings are thrown:

Warning: opf_is_registered(): Filter not registred: Cache Control in /.../modules/outputfilter_dashboard/functions.php on line 673
Warning: opf_is_registered(): Filter not registred: Correct Date Format in /.../modules/outputfilter_dashboard/functions.php on line 673
Warning: opf_is_registered(): Filter not registred: Short URL in /.../modules/outputfilter_dashboard/functions.php on line 673
Warning: opf_is_registered(): Filter not registred: Sys Rel in /.../modules/outputfilter_dashboard/functions.php on line 673
Warning: opf_is_registered(): Filter not registred: Insert in /.../modules/outputfilter_dashboard/functions.php on line 673
Warning: opf_is_registered(): Filter not registred: Auto Placeholder in /.../modules/outputfilter_dashboard/functions.php on line 673
Warning: opf_is_registered(): Filter not registred: Droplets in /.../modules/outputfilter_dashboard/functions.php on line 673
Warning: opf_is_registered(): Filter not registred: CSS to head in /.../modules/outputfilter_dashboard/functions.php on line 673
Warning: opf_is_registered(): Filter not registred: WB-Link in /.../modules/outputfilter_dashboard/functions.php on line 673

The script finishes, but! in the frontend of the updated site appears
[[Title]] [[Metas]] [[Css]] [[Js?pos=HeadTop]] [[Js?pos=HeadLow]] [[Js?pos=BodyTop]] [[Html?pos=BodyTop]] 

So at least the setting "Platzhalter für fehlende Insertfilter einfügen:" should be set to deactivated by default.

**Comment by NorHei** [comment]
Handled this to Martin

**Comment by instantflorian** [comment]
Sorry, but this is rather urgent.

**Comment by mrbaseman** [comment]
yes. I'm looking into this, but didn't find the root cause for the problem, yet. During the upgrade we have to register the module filters in opf and during this process at one point one of the functions involved calls another one which assumes that the filter is already registered. The warning is on purpose, so that the author of the module (in this case myself) gets notified that something needs to be fixed. However, it turns out that the line number is not very helpful, so I have to change the error handling such that it is easier to spot the root cause. I'll do that with high priority.

**Comment by mrbaseman** [comment]
with 1711d06 the warnings are suppressed (unless DEBUG is defined as TRUE). So, the upgrade script is quiet now. Unfortunately, I could not (yet) find the root cause for these warnings. They come from opf_set_active, which is called after the filter is registered. So, theoretically, the warning should not appear at all. Looking at the database after the upgrade, the filters have been registered successfully, so for some reason opf_is_registered is giving a false alarm, based on the result of its query to the database. 
I'm going to investigate this further, and I still hope that I can find the root cause for this strange behavior. 
Anyhow, since you guys are working so much on WBCE I had the feeling that I should already make this partial fix public, together with a few other improvements

**Comment by NorHei** [comment]
good idea , we leave this open for now

**Comment by mrbaseman** [comment]
the problem were the opf_db_ functions which have checked `$database->is_error()` which works fine if no error has occurred, but which fails (at least in some cases) if previous queries have failed. in 1.5.4 I check the result of the query command directly. If it returns NULL it is a more reliable sign that the **current** query has failed. Now the error messages during OpF installation are gone, even when I `define(DEBUG, TRUE)`.

**Comment by NorHei** [comment]
Any idea whats wrong whith `$database->is_error()`?

Am 20.04.2017 um 00:10 schrieb Martin Hecht:
> the problem were the opf_db_ functions which have checked `$database->is_error()` which works fine if no error has occurred, but which fails (at least in some cases) if previous queries have failed. in 1.5.4 I check the result of the query command directly. If it returns NULL it is a more reliable sign that the **current** query has failed. Now the error messages during OpF installation are gone, even when I `define(DEBUG, TRUE)`.
>

-- 
Norbert Heimsath
Mergelstraße 25
45478 Mülheim an der Ruhr
0208 55 792

**Comment by mrbaseman** [comment]
credits to @NorHei for identifying the root cause of this issue. I could verify it in my environment and commited the fix in e4fa8ee in addition to the workaround inside of the module already implemented
