### ISSUE TITLE
Fresh install of 1.2, all OPF are missing in the BE

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#248]
Looking into the sourcecode, there appears
[[Js?pos=HeadLow]]
![opf](https://cloud.githubusercontent.com/assets/1433754/24839388/a46a4a10-1d59-11e7-955b-14929db11cfc.jpg)
![opf2](https://cloud.githubusercontent.com/assets/1433754/24839390/c0a15c82-1d59-11e7-99ba-48e2e270d77a.jpg)

**Comment by NorHei** [comment]
7ca18b4  schould have done the job

**Comment by instantflorian** [comment]
As far as I can see, the mentioned commit concerns only my last changes which have nothing to do with OPF?

**Comment by NorHei** [comment]
4f0156d29df2b4c48c5935b1963b848d08d612e7

Sorry this was it

**Comment by mrbaseman** [comment]
I think the only thing we need from the classical output_filter module is the upgrade script and that could be included (i.e. copy&paste the content) into the WBCE upgrade script.

**Comment by mrbaseman** [comment]
sorry, looking at the tilte of this issue I must correct myself: at least parts of the install script are probably needed, too

**Comment by mrbaseman** [comment]
I have tried to reproduce this with current branch 1.2.x (latest commit 95f3a99) and deleted the output_filter folder before running the install script. 
It seems the output filters of the dashboard are not applied to all backend pages.  
I have noticed that the opf_controller function is not known in the backend. 

The solution is to include  WB_PATH . '/modules/outputfilter_dashboard/functions.php'  just before calling opf_controller in class.admin.php and class.tool.php. 

I still need to check which parts of the installer and the upgrade scripts of the output_filter module are needed. Also, automatic uninstall of output_filter during WBCE upgrade is needed. Once I have all this, I'll push a solution that covers the side effects.

**Comment by mrbaseman** [comment]
I have just implemented what I have described in my previous comment (this is the main fix for this issue). Apart from that I have rearranged the install/upgrade scripts of the filter modules a bit so that the correct steps should be executed for the three cases

1. fresh installation (no previous settings/database table present)
2. upgrade from a previous version and no dashboard installed
3. upgrade where the dashboard have been installed (either manually or in the future, when upgrading  1.2.x -> 1.2.x++)

and finally I have removed the output_filter folder and adapted the upgrade script so that stuff is imported into the individual modules, then the classical output filter is uninstalled and finally the folder is removed if it was present.
I have also done some cleanup (mostly white spaces) when touching all the opf modules and incremented the version numbers. Closing this issue for now.
If I have broken something with my series of commits, please complain and reopen.
