### ISSUE TITLE
Fatal Error at Grundeinstellungen > System

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#252]
Fatal error: Uncaught Error: Call to undefined function ds_GetTemplatesArray() in /.../modules/settings_general/templates/general.tpl.php:214 Stack trace: #0 /.../modules/settings_general/tool.php(325): include() #1 /.../framework/classes/class.tool.php(277): require('/var/www/web913...') #2 /.../admin/settings/tool.php(16): Tool->Process(true) #3 {main} thrown in /.../modules/settings_general/templates/general.tpl.php on line 214

**Comment by NorHei** [comment]
... wenn man bitte was aufruft ?

**Comment by NorHei** [comment]
ahh got it ..

**Comment by cwsoft** [comment]
Error still exists in Settings -> General Settings (see screenshot)

<img width="634" alt="settings-general" src="https://cloud.githubusercontent.com/assets/1426817/25301818/e604689e-2730-11e7-9a67-0515556d75a8.PNG">

**Comment by NorHei** [comment]
Ahhh got it Argos reloaded uses its own template for Displaying the module 
so everything looked perfectly ok .. fixing it

**Comment by NorHei** [comment]
Argos reloaded wird auch angepasst

**Comment by mrbaseman** [comment]
I still see a similar error when switching to argos_reloaded:
`Fatal error: Uncaught Error: Call to undefined function ds_TemplatePossible() in .../modules/settings_general/tool.php:229 Stack trace: #0 .../framework/classes/class.tool.php(277): require() #1 .../admin/settings/index.php(16): Tool->Process(true) #2 {main} thrown in .../modules/settings_general/tool.php on line 229`
hmmm... 

another small issue: if you go to "Grundeinstellungen" in wb_flat you can click on the title of each settings module, but there is also the small icon at the bottom right of each module where the link still literally contains '$toolLink' ... and there is a php comment which is still sent out to the user (`<?` used instead of `<?php` somewhere):

`
                    
                    <table id="former_positioning_table">
                        <tr>
                            <td class="content"><?
/**
Tools list Tempalte
*/
//no direct file access
if(count(get_included_files())==1) die(header("Location: ../index.php",TRUE,301));


?>

<div id="page_admintools">
    <h2 class="page_titel">Grundeinstellungen</h2>
    <div id="admintools">
        <div class="dynamicGrid-outer">
    
 
            <div class="admintools_tool themebox dynamicGrid_2">
                <div class="tb_header" >            
                    <i class="fa fa-cogs"></i><a href=".../admin/settings/tool.php?tool=settings_defaults"></a>
                </div>          
                <div class="tb_content_outer">
                    <div class="tb_content" style="height:115px; overflow:hidden; padding-right:45px; margin-bottom:5px;">          
                        <a class="tb_titel"  href=".../admin/settings/tool.php?tool=settings_defaults">Standardwerte</a>
                        Sprache, Zeitzone, Datums- und Uhrzeitformat              
                    </div>
                </div>         
                <div class="tb_footer">
                    <a href="$toolLink"></a>
                </div>
            </div>
`

**Comment by Colinax** [comment]
@mrbaseman the similar error is already reported in #256 

I can confirm your other small issue
