### ISSUE TITLE
Check FTAN in News and Form module

### ISSUE THREAD

**Issue by webbird** [WBCE/WebsiteBaker_CommunityEdition#56]
FTAN support was added in WB Classic in SP5, we must check if we have to add it, too.

**Comment by NorHei** [comment]
Yes we may add it too, but please don't use the the SP5 implementation as its more or less broken by dessign. Simply adding 
$wb->getFTAN(); 
and 
if (!$wb->checkFTAN($tan)) Do something; 
should do the job .

**Comment by webbird** [comment]
Ah. I wondered why my code in Bookings module does not work... It only calls $wb->getFTAN() which does a return instead of echo. Is this what you mean with broken?

**Comment by NorHei** [comment]
Nope , SP5 seems to rely on another class and add strange loaders on index ,php .
The whole idea is Broken by design.  Either we schould use a class like CSRF Magick . 
Or have this thing as a plain Static method .  In addition the idea of generating one Tan per page and handing this to all forms simply sucks. The whole thing is distorted and strange .

The change to retvalue was made somewhere between SP1 and SP4.

$wb->getFTAN(true|false); 
and 
if (!$wb->checkFTAN("POST|GET")) Do something; 
 
is still 
 the correct way

**Comment by Colinax** [comment]
We don't' ship Form and News in the Download Package, so it's closed.
