### ISSUE TITLE
Backup tool

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#86]
Error:
- Database dump and file system backup are displayed in browser instead of offered as a sql-/zip-file to download 

Enhancements:
- Language file has to be reworked ("Sicherung nur der von >>>WebsiteBaker<<< generierten Tabellen")
- annoying JS alert should be replaced by an information on screen
- it should be possible to select/deselect directories which should (not) be backupped to avoid timeouts (e.g. "media" or "piwik")

**Comment by NorHei** [comment]
Error:
 Can not reproduce error in latest master (fresh install), check if its latest Master , otherwise i need to take a look on that server.

Can you please look after the Language file ?


- annoying JS alert should be replaced by an information on screen
- it should be possible to select/deselect directories which should (not) be backupped to avoid timeouts (e.g. "media" or "piwik")

Both good ideas , can you please open a nother issue for them ?

**Comment by instantflorian** [comment]
Error still exists (fresh install).
Will send you access data by mail then you can have a look on it.

Updated the language fuiles and placed the patience-info from the alert 
in the body.

**Comment by NorHei** [comment]
7bd62ed  I close this , please add another issue for the other enhancements
