### ISSUE TITLE
Cloning droplets

### ISSUE THREAD

**Issue by NorHei** [WBCE/WebsiteBaker_CommunityEdition#88]
When i try to Clone Droplets i get a nice bunch of errors .
![screenshot - 05 01 2016 - 22 31 51](https://cloud.githubusercontent.com/assets/1908651/12128598/991eb850-b3fe-11e5-8029-63b842d18012.png)

**Comment by qssocial** [comment]
hehe:)
use $database->get_one("SELECT LAST_INSERT_ID()");

Krzysztof

**Comment by NorHei** [comment]
Done 6d54341.

Do you want a job in WB(CE) development? But i fear it not paid at all ;-)

And Maybe you like to take a look at this , they seem to have problems whith installing droplets out of a module . http://forum.wbce.org/viewtopic.php?pid=2836#p2836

**Comment by qssocial** [comment]
Where can I get a pro calendar?
At the end of the week I'll see what it is.
Now I have to do two websites.

Mainly I programmed in Delphi XE.
Now sometimes in PHP, HTML ...

Sorry for my English. I learn hehe :)
I am from Poland but has recently moved to Chicago.

**Comment by NorHei** [comment]
http://addons.wbce.org/?do=item&item_id=19

Your english is good enough , and i guess its even getting better every day , as you have no choice other than using it ;-)

Is there another  way to communicate whith you, not  via this bugtracker ?

Damm its late getting tired , Good Night !

**Comment by qssocial** [comment]
Yes
The problem of programmers :)
I'll give you an e-mail tomorrow
Good Night

**Comment by qssocial** [comment]
First please correct class.admin 114
                    if (OPF_SHORT_URL) {$ view_url = WB_URL. $ row ['link']; }
to
if (OPF_SHORT_URL) {$view_url = WB_URL. $row ['link']; }
Copy from browser make truble :)

Droplets.....
I got in admin droplets
Notice: Undefined variable: description in D:\Programming\www\wamp22ap1\www\wbce12\modules\droplets\functions.inc.php on line 205

Notice: Undefined variable: usage in D:\Programming\www\wamp22ap1\www\wbce12\modules\droplets\functions.inc.php on line 205

Very important:
You should always initialize variables if they are added to the database.
Sometimes the droplets headline is wrong such no //usage, //description

solution
line 184 ...
                    $description = ""; //add 
                    if ( preg_match( '#^//\:(.*)$#', $lines[0], $match ) ) {
                        $description = $match[1];
                    }
                    // Second line: Usage instructions
                    $usage = ""; //add
                    if ( preg_match( '#^//\:(.*)$#', $lines[1], $match ) ) {
                        $usage       = addslashes( $match[1] );
                    }

Next problem from forum ( not for me)
Import über Admintools
Notice: Undefined index: Upload failed in \modules\droplets\functions.inc.php on line 123

Probably the problem is with permission.
I once had a similar problem, because he was zip folder with the files. Removal helped.
I think it should before Upload:
1. Check whether there is a folder temp and temp/zip.
2. If there is no create Temp (mkdir) and delete zip

line 115        $temp_dir   = WB_PATH.'/temp/';
        $temp_file  = $temp_dir . $_FILES['userfile']['name'];
        $temp_unzip = WB_PATH.'/temp/unzip/';
        $errors     = array();
// check folder temp/mkdir/delete zip
        // Try to upload the file to the temp dir
        if( ! move_uploaded_file( $_FILES['userfile']['tmp_name'], $temp_file ) )



Next problem.
Warning: strpos(): Empty needle in D:\Programming\www\wamp22ap1\www\wbce12\admin\modules\install.php on line 188
Invalid WebsiteBaker installation file. Please check the *.zip format.

But addons module installs perhaps the only module not droplets. No install.php file.
Am I wrong?

Krzysztof

**Comment by NorHei** [comment]
I know that you should always initialize vars ... :-)
Tell this to my predecessors ;-)

Basically we should decide to have a good upload class available in the core ;-)

The install file is not needed for all modules , but droplets certainly has one . 

The last two seem to be a path issue but its hard to say whithout being able to reproduce the error . So how do i reproduce it ?

**Comment by NorHei** [comment]
Warning: Cannot modify header information - headers already sent by (output started at /var/www/web207/html/wbce_norbert_heimsath_de/modules/phplib/classes/phplib/template.inc:668) in /var/www/web207/html/wbce_norbert_heimsath_de/modules/droplets/manage_backups.php on line 61

ok fixed it right now ..

**Comment by qssocial** [comment]
Maybe they used national characters such as umlauts or space. Then you should use '' ".
It is possible that the file system server configuration is different than the characters used.
You can try to use space and national characters in the name of files and folders.
Maybe it is a problem.

**Comment by qssocial** [comment]
Where to leave my e-mail
Krzysztof

**Comment by NorHei** [comment]
You have a forum account send me a PM (norhei), or use the contact button on my homepage (heimsath.org) The little mail icon up right.

**Comment by webbird** [comment]
If it's okay for all I will do a complete review and rework of the droplets module, which will result in v1.8. I'll create a new issue for this.

**Comment by NorHei** [comment]
I guess i close this one then.
